import Head from 'next/head'
import { questions } from "../lib/data"
import QuestionsBuilder from "../lib/questionsBuilder"
import styles from '../styles/Home.module.css'


export default function Home({ questionsList }) {
  return (
    <div>
      <Head>
        <title>Formulario</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.card}>
          <h2>Formulario</h2>
          <form action="/api/posts" method="post" autoComplete="off">
            <div>
              {questionsList.map(question => (
                <QuestionsBuilder 
                  key={question.id} 
                  type={question.type} 
                  body={question.body} 
                  name={question.name}
                />                
              ))}
            </div>
            <div className={styles.button}>
              <button type="submit">Enviar</button>
            </div>
          </form>
        </div>
      </main>
    </div>
  )
}

export const getStaticProps = async () => {
  return {
    props:{
      questionsList: questions,
    },
  }
}
